export {default as Login} from './Login';
export {default as Home} from './Home';
export {default as Signup} from './Signup';
export {default as AdminLogin} from './AdminLogin';
export {default as AdminHome} from './AdminHome';
export {default as AdminSignup} from './AdminSignup';
export {default as VisitorForm} from './VisitorForm';
export {default as CurrentVisitors} from './CurrentVisitors' ; 
export {default as PreviousVisitors} from './PreviousVisitors' ; 
export {default as StudentVisitorForm} from './StudentVisitorForm';
export {default as CurrentStudentVisitors} from './CurrentStdVis' ; 
export {default as PreviousStudentVisitors} from './PreviousStudentV' ; 
export {default as Navbar} from './Navbar' ; 
